# Generated by Django 3.1.5 on 2021-04-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='web',
            field=models.CharField(max_length=50),
        ),
    ]
