# Generated by Django 3.1.5 on 2021-04-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210421_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='web',
            field=models.URLField(max_length=50),
        ),
    ]
