# Generated by Django 3.1.5 on 2021-05-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210421_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='xss',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
