# Generated by Django 3.1.5 on 2021-05-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210507_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xss', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='website',
            name='xss',
        ),
    ]
