# Generated by Django 3.1.5 on 2021-05-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_qna_qna1_qna2_qna3_qna4_qna5_qna6_qna7_qna8_qna9'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QNA',
        ),
        migrations.DeleteModel(
            name='QNA1',
        ),
        migrations.DeleteModel(
            name='QNA2',
        ),
        migrations.DeleteModel(
            name='QNA3',
        ),
        migrations.DeleteModel(
            name='QNA4',
        ),
        migrations.DeleteModel(
            name='QNA5',
        ),
        migrations.DeleteModel(
            name='QNA6',
        ),
        migrations.DeleteModel(
            name='QNA7',
        ),
        migrations.DeleteModel(
            name='QNA8',
        ),
        migrations.DeleteModel(
            name='QNA9',
        ),
    ]
