# Generated by Django 3.1.5 on 2021-05-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_qna'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.DeleteModel(
            name='Xss',
        ),
    ]
